language: node_js
node_js:
  - "0.10"
  - "0.11"
env:
  global:
    - GH_REF: github.com/andrewblond/bem-walk.git
    - ISTANBUL_COVERAGE: true
branches:
  only:
    - master
after_success:
  - npm i coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && echo "Coverage data was sent to coveralls!"
