language: node_js
node_js:
  - "0.10"
env:
  global:
    - GH_REF: github.com/bem/bem-naming.git
    - ISTANBUL_COVERAGE: true
    - secure: EmjCayFf+5jyXRLtH2lTLRIqXSyM23PwS+KceyX/Nwppd0ReMzR+rCnx7oFCydrmjlKFiHF6eLVs/3VcPEtLhz3wat/h0iU5eSOW6vaH/6tBeKFj8UuN5TPOEKENyCwUmV4QL4j+RbYSNWdAZ/rFu8Y3hPDmtAgXKCj7QvPxsms=
    - secure: RNUlSmfxd1qKybLELKM2uiheyLHbqfDoP5v7rjnaLwaddURwhqFfV1SYxV+ei5COrlr1waeV4k62UKJNYNWRin29o6LAjbHQGnNX1bSaCYgw8SQWZerpRXr0NQ1v8jVcJzj7CBbyG4nyAYeQDWxj6gNswz6K5uQkuNnLiepK1pA=
branches:
  only:
    - master
after_success:
  - npm i coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && echo "Coverage data was sent to coveralls!"
