sudo: false

branches:
  only:
  - master

language: node_js

matrix:
  include:
    - node_js: "4"
    - node_js: "6"
      env: COVERALLS=1
    - node_js: "8"
      env: NPM_4=1

before_install:
  - if [ "x$NPM_4" = "x1" ]; then
      npm install -g npm@4;
      npm -v;
    fi

install:
  - npm install
  - lerna bootstrap

after_success:
  - if [ "x$COVERALLS" = "x1" ]; then
      npm i coveralls;
      nyc report --reporter=text-lcov | coveralls;
    fi
