ui: mocha-bdd
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: latest
  - name: ie
    version: 9..latest
scripts:
  - "./node_modules/should/should.js"
